# General Jekyll Config
markdown: kramdown
pygments: true
url: http://fengmengzhao.github.io
baseurl: /blogs
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
# Theme customization - please change from the defaults!
profile:
  # Color for top bar, links, etc
  highlight_color: '#3498db'
  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: FengMengZhao
    twitter: fengmengzhao
    facebook: 100008350779619
    gplus: 105478354193409781551
  # "Hi, I'm _______"
  name: 麦羞
  email: fengmengzhao@gmail.com
  tagline: "weak opinions, strongly held"
  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-34087103-1
  google_analytics_domain: 'lenage.com'
  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
